title: Daniel PÃ©rez
logo: /assets/img/Daniel_circle.png
#description:
description: ğŸ’¼Ingeniero con 9 aÃ±os de experiencia en proyectos tecnolÃ³gicos en diversas plataformas para el sector minerÃ­a, educaciÃ³n, social, salud, banca, gas y energÃ­a. ğŸ““Autor y revisor de artÃ­culos cientÃ­ficos sobre inteligencia artificial, IoT, automatizaciÃ³n de procesos, procesamiento de imÃ¡genes y blockchain. ğŸ‘¨â€ğŸ«CatedrÃ¡tico universitario, asesor y jurado de tesis.
show_downloads: false
theme: jekyll-theme-minimal
